server:
  port: ${APP_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: hspd # Historical stock prices data
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:prod}

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

token:
  signing:
    key: ${SIGNING_KEY}

polygonAPI:
  url: "https://api.polygon.io/v2/aggs/ticker/%s/range/1/day/%s/%s?"
  apiKey: ${API_KEY}

bcrypt:
  strength: 12
