server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: HSPD
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

token:
  signing:
    key: ${tokenJWT}