spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://db:5432/postgres}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
    redis:
      time-to-live: ${token.ttl.access:86400000}ms
  data:
    redis:
      host: redis
      port: ${RD_PORT:6379}
