server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: hspd # Historical stock prices data
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        batch_fetch_style: dynamic
        default_batch_fetch_size: 50
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?reWriteBatchedInserts=true
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    root: info

token:
  signing:
    key: ${tokenJWT}

polygonAPI:
  url: "https://api.polygon.io/v2/aggs/ticker/%s/range/1/day/%s/%s?"
  apiKey: ${APIKey}

bcrypt:
  strength: 12
