server:
  port: ${APP_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: hspd # Historical stock prices data
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:prod}
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 450
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        batch_fetch_style: dynamic
        default_batch_fetch_size: 450
        generate_statistics: false # batch check
  cache:
    type: redis
    redis:
      time-to-live: ${token.ttl.access:86400000}ms
  data:
    redis:
      host: localhost
      port: ${RD_PORT:6379}

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

token:
  signing:
    key: ${SIGNING_KEY}
  ttl:
    access: 86400000 # 1000 * 60 * 60 * 24
    refresh: 604800000 # 1000 * 60 * 60 * 24 * 7

polygonAPI:
  url:
    main: "https://api.polygon.io/v2/aggs/ticker/%s/range/1/day/%s/%s?"
    ticker.details: "https://api.polygon.io/v3/reference/tickers/%s"
  apiKey: ${API_KEY}

bcrypt:
  strength: 12
