-- liquibase formatted sql

-- changeset Toxaencom1:1736510294885-1
CREATE TABLE "roles"
(
    "id"    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "roles" VARCHAR(255),
    CONSTRAINT "roles_pkey" PRIMARY KEY ("id")
);

-- changeset Toxaencom1:1736510294885-2
CREATE TABLE "users"
(
    "id"       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "username" VARCHAR(60),
    "password" VARCHAR(255),
    "email"    VARCHAR(255),
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- changeset Toxaencom1:1736510294885-3
ALTER TABLE "users"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");

-- changeset Toxaencom1:1736510294885-4
ALTER TABLE "users"
    ADD CONSTRAINT "users_username_key" UNIQUE ("username");

-- changeset Toxaencom1:1736510294885-5
CREATE TABLE "permission"
(
    "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" VARCHAR(255),
    CONSTRAINT "permission_pkey" PRIMARY KEY ("id")
);

-- changeset Toxaencom1:1736510294885-6
CREATE TABLE "permission_roles"
(
    "roles_id"       BIGINT NOT NULL,
    "permissions_id" BIGINT NOT NULL
);

-- changeset Toxaencom1:1736510294885-7
CREATE TABLE "users_roles"
(
    "user_id"  BIGINT NOT NULL,
    "roles_id" BIGINT NOT NULL
);

-- changeset Toxaencom1:1736510294885-8
ALTER TABLE "users_roles"
    ADD CONSTRAINT "fk2o0jvgh89lemvvo17cbqvdxaa" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Toxaencom1:1736510294885-9
ALTER TABLE "permission_roles"
    ADD CONSTRAINT "fk4x1ep59ihlibm5jnhb5t8y2hv" FOREIGN KEY ("roles_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Toxaencom1:1736510294885-10
ALTER TABLE "permission_roles"
    ADD CONSTRAINT "fk9lqx45njk0pt5lcux4lqewijk" FOREIGN KEY ("permissions_id") REFERENCES "permission" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Toxaencom1:1736510294885-11
ALTER TABLE "users_roles"
    ADD CONSTRAINT "fka62j07k5mhgifpp955h37ponj" FOREIGN KEY ("roles_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

