-- liquibase formatted sql

-- changeset Toxaencom1:1736510294885-23
create table refresh_tokens
(
    id            bigint generated by default as identity
        primary key,
    refresh_token varchar(255)
);